#!/bin/bash

set -e

TODAY=$(date "+%Y-%m-%d")
BIRTHDAYS="${PWD}/birthdays.txt"

function main()
{
    for birthday in $(cat ${BIRTHDAYS} | grep '[1-2][0-9][0-9][0-9]-[0-2][0-9]-[0-3][0-9]' ); do

        local msg
        local date
        local name
        local email

        date=$( echo "${birthday}" | cut -d ',' -f1)
        name=$( echo "${birthday}" | cut -d ',' -f2)
        email=$( echo "${birthday}" | cut -d ',' -f3)

        if [[ "${date:5:5}" == "${TODAY:5:5}" ]]; then
            msg="Happy birthday ${name}!
            This message was generated by the Birthday Alert System!"
        else
            msg="Sorry ${name}, ${TODAY} is not your birthday :("
        fi

        echo "${msg}"
    done

}

main
